version: "3.8"

services:
  validator:
    image: thebes1618/affine:latest
    container_name: affine-validator
    restart: unless-stopped
    mem_reservation: "6g"
    mem_limit:       "8g"
    env_file:
      - .env
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - /var/log/affine/validator:/var/log/affine/validator
    command: ["-vv", "services", "validator"]

  watchtower:
    image: nickfedor/watchtower
    container_name: affine-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 affine-validator
